const types = {
  // actions
  GET_BANNER: 'GET_BANNER',
  GET_RECOMMEND_PLAYLIST: 'GET_RECOMMEND_PLAYLIST',
  GET_RECOMMEND_PLAYLIST_DETAIL: 'GET_RECOMMEND_PLAYLIST_DETAIL',
  GET_RECOMMEND_MUSIC: 'GET_RECOMMEND_MUSIC',
  GET_RANK: 'GET_RANK',
  GET_ARTIST: 'GET_ARTIST',
  GET_MUSIC_URL: 'GET_MUSIC_URL',
  GET_MUSIC_LYRIC: 'GET_MUSIC_LYRIC',
  GET_IDX_MUSIC: 'GET_IDX_MUSIC',
  // mutations
  SET_STATECTRL: 'SET_STATECTRL',
  SET_LOADINGCTRL: 'SET_LOADINGCTRL',
  SET_PLAYER_INI: 'SET_PLAYER_INI',
  SET_CURR_IDX: 'SET_CURR_IDX',
  SET_MUSIC_QUEUE: 'SET_MUSIC_QUEUE',
  SET_PUSH_MUSIC_QUEUE: 'SET_PUSH_MUSIC_QUEUE',
  SET_DEL_MUSIC_QUEUE: 'SET_DEL_MUSIC_QUEUE',
  SET_BANNER_LIST: 'SET_BANNER_LIST',
  SET_RECOMMEND_PLAYLIST: 'SET_RECOMMEND_PLAYLIST',
  SET_PLAYLIST_DETAIL: 'SET_PLAYLIST_DETAIL',
  SET_RECOMMEND_MUSIC: 'SET_RECOMMEND_MUSIC',
  SET_RANK_LIST: 'SET_RANK_LIST',
  SET_ARTIST_LIST: 'SET_ARTIST_LIST'
}

export default types
